# Based on https://github.com/prettier/prettier/blob/master/.github/workflows/dev-test.yml
name: Dev

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        python-version:
            - 3.6
            - 3.7
            - 3.8
        include:
          # only enable coverage on the fastest job
          - os: "ubuntu-latest"
            python: "3.7"
            ENABLE_CODE_COVERAGE: true
    env:
      ENABLE_CODE_COVERAGE: ${{ matrix.ENABLE_CODE_COVERAGE }}
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Create virtual python environment
        run: python -m venv venv

      - name: Activate virtual environment (Linux/MacOS)
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        run: . venv/bin/activate
      - name: Activate virtual environment (Windows)
        if: matrix.os == 'windows-latest'
        run: venv\Scripts\Activate.ps1


      - name: Display Pip Version
        run: pip -V
      - name: Install Dev Dependencies
        run: pip install -r requirements-dev.txt
      - name: Install Main Package
        run: pip install -e .
      - name: Log full installed packages
        run: pip freeze
      - name: Install pre-commit hooks
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.7
        # only enable pre-commit on the fastest job
        run: pre-commit install

      - name: Run pre-commit hooks
        # only enable pre-commit on the fastest job
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == 3.7
        run: pre-commit run -a

      - name: Run Tests
        run: pytest -xsvv

      - name: Confirm Sphinx Docs build correctly
        run: SPHINXOPTS="-W" make --directory=docs html # the -W flag treats warnings as errors to cause build failures
